// export enum ENTITY_NAME {
//   appConfig = "appConfig",
//   audit = "audit",
//   authorizer = "authorizer",
//   client = "client",
//   config = "config",
//   database = "database",
//   detail = "detail",
//   group = "group",
//   metrics = "metrics",
//   health = "health",
//   log = "log",
//   organization = "organization",
//   project = "project",
//   questionnaire = "questionnaire",
//   permission = 'permission',
//   protocol = "protocol",
//   revision = "revision",
//   role = "role",
//   source = "source",
//   sourceData = "sourceData",
//   sourceType = "sourceType",
//   subject = "subject",
//   user = "user",
//   uploadPortal = "uploadPortal",
//   dataStorage = "dataStorage",
//   systemMonitor = "systemMonitor",
//   systemLogs = "systemLogs",
//   website = "website",
//   wiki = "wiki",
//   systemStatus = "systemStatus",
//   grafana = "grafana",
// }

export enum ROLES {
  SYS_ADMIN = 'ROLE_SYS_ADMIN',
  ORGANIZATION_ADMIN = 'ROLE_ORGANIZATION_ADMIN',
  PROJECT_ADMIN = 'ROLE_PROJECT_ADMIN',
}

