export enum QuestionTypes {
  RADIO = 'radio',
  YESNO = 'yesno',
  CHECKBOX = 'checkbox',
  TEXT = 'text',
  RANGE = 'range',
  RANGE_INFO = 'range-info',
  SLIDER = 'slider',
  INFO = 'info',
  DESCRIPTIVE = 'descriptive',
  AUDIO = 'audio',
  TIMED = 'timed',
  MATRIX_RADIO = 'matrix-radio',
  DATETIME = 'datetime',
}

export const QUESTION_TYPES = [
  {name: QuestionTypes.RADIO, label: 'Radio'},
  {name: QuestionTypes.YESNO, label: 'Yes/No'},
  {name: QuestionTypes.CHECKBOX, label: 'Checkbox'},
  {name: QuestionTypes.TEXT, label: 'Text Input'},
  {name: QuestionTypes.DATETIME, label: 'Date/Time Input'},
  {name: QuestionTypes.INFO, label: 'Info'},
  {name: QuestionTypes.DESCRIPTIVE, label: 'Descriptive'},
  {name: QuestionTypes.SLIDER, label: 'Slider'},
  {name: QuestionTypes.RANGE, label: 'Range'},
  {name: QuestionTypes.RANGE_INFO, label: 'Range Info'},
  {name: QuestionTypes.MATRIX_RADIO, label: 'Radio-Matrix'},
  {name: QuestionTypes.TIMED, label: 'Timed'},
  {name: QuestionTypes.AUDIO, label: 'Audio'},
];
