export enum ENTITY_NAME {
  appConfig = "appConfig",
  audit = "audit",
  authorizer = "authorizer",
  client = "client",
  config = "config",
  database = "database",
  detail = "detail",
  group = "group",
  metrics = "metrics",
  health = "health",
  log = "log",
  organization = "organization",
  project = "project",
  questionnaire = "questionnaire",
  permission = 'permission',
  protocol = "protocol",
  revision = "revision",
  role = "role",
  source = "source",
  sourceData = "sourceData",
  sourceType = "sourceType",
  subject = "subject",
  user = "user",
  uploadPortal = "uploadPortal",
  dataStorage = "dataStorage",
  systemMonitor = "systemMonitor",
  systemLogs = "systemLogs",
  website = "website",
  wiki = "wiki",
  systemStatus = "systemStatus",
  grafana = "grafana",
}
// export enum ENTITIES_ICONS {
//   audit = "notifications",
//   client = "app_shortcut",
//   config = "app_settings_alt",
//   database = "storage",
//   detail = "article",
//   group = "portrait",
//   health = "monitor_heart",
//   log = "source",
//   metrics = "speed",
//   organization = "corporate_fare",
//   project = "folder",
//   protocol = "pending_actions",
//   questionnaire = "content_paste",
//   role = "manage_accounts",
//   revision = "history",
//   source = "source",
//   sourceData = "snippet_folder",
//   sourceType = "folder_special",
//   subject = "person_outline",
//   subjectAuthorizer = "",
//   subjectRevision = "",
//   user = "person",
// }
//
// export enum ENTITIES_ROUTES {
//   audit = "/admin/audits",
//   client = "/admin/clients",
//   config = "",
//   database = "/admin/databases",
//   detail = "",
//   group = "",
//   metrics = "/admin/metrics",
//   health = "/admin/health",
//   log = "/admin/logs",
//   organization = "/admin/organizations",
//   project = "",
//   questionnaire = "/admin/questionnaires",
//   protocol = "/admin/protocols",
//   role = "",
//   revision = "/admin/revisions",
//   source = "",
//   sourceData = "/admin/source-data",
//   sourceType = "/admin/source-types",
//   subject = "",
//   user = "/admin/users",
// }
//
export enum ROLES {
  SYS_ADMIN = 'ROLE_SYS_ADMIN',
  ORGANIZATION_ADMIN = 'ROLE_ORGANIZATION_ADMIN',
  PROJECT_ADMIN = 'ROLE_PROJECT_ADMIN',

}

