import { ENTITY_NAME } from "../enums/entities";

export const ENTITIES: Record<ENTITY_NAME, {name: ENTITY_NAME, icon: string; route: string;}> = {
  [ENTITY_NAME.appConfig]: {name: ENTITY_NAME.appConfig, icon: "app_settings_alt", route: "/admin/global-configs/apps"},
  [ENTITY_NAME.audit]: {name: ENTITY_NAME.audit, icon: "policy", route: "/admin/audits"},
  [ENTITY_NAME.authorizer]: {name: ENTITY_NAME.authorizer, icon: "person_outline", route: ""},
  [ENTITY_NAME.client]: {name: ENTITY_NAME.client, icon: "important_devices", route: "/admin/clients"},//important_devices //devices_other
  [ENTITY_NAME.config]: {name: ENTITY_NAME.config, icon: "app_settings_alt", route: ""},
  [ENTITY_NAME.database]: {name: ENTITY_NAME.database, icon: "storage", route: "/admin/databases"},
  [ENTITY_NAME.detail]: {name: ENTITY_NAME.detail, icon: "article", route: ""},
  [ENTITY_NAME.group]: {name: ENTITY_NAME.group, icon: "portrait", route: ""},
  [ENTITY_NAME.metrics]: {name: ENTITY_NAME.metrics, icon: "troubleshoot", route: "/admin/metrics"},
  [ENTITY_NAME.health]: {name: ENTITY_NAME.health, icon: "heart_check", route: "/admin/health"},
  [ENTITY_NAME.log]: {name: ENTITY_NAME.log, icon: "description", route: "/admin/logs"},
  [ENTITY_NAME.organization]: {name: ENTITY_NAME.organization, icon: "corporate_fare", route: "/admin/organizations"},
  [ENTITY_NAME.project]: {name: ENTITY_NAME.project, icon: "folder_open", route: "/admin/projects"},
  [ENTITY_NAME.questionnaire]: {name: ENTITY_NAME.questionnaire, icon: "pending_actions", route: "/admin/questionnaires"},
  [ENTITY_NAME.protocol]: {name: ENTITY_NAME.protocol, icon: "content_paste", route: "/admin/protocols"},
  [ENTITY_NAME.revision]: {name: ENTITY_NAME.revision, icon: "history", route: "/admin/revisions"},
  [ENTITY_NAME.role]: {name: ENTITY_NAME.role, icon: "history", route: "/admin/revisions"},
  [ENTITY_NAME.source]: {name: ENTITY_NAME.source, icon: "source", route: ""},
  [ENTITY_NAME.sourceData]: {name: ENTITY_NAME.sourceData, icon: "schema", route: "/admin/source-data"}, //snippet_folder
  [ENTITY_NAME.sourceType]: {name: ENTITY_NAME.sourceType, icon: "category", route: "/admin/source-types"},
  [ENTITY_NAME.subject]: {name: ENTITY_NAME.subject, icon: "person_outline", route: ""},
  [ENTITY_NAME.user]: {name: ENTITY_NAME.user, icon: "person", route: "/admin/users"},
  [ENTITY_NAME.dataStorage]: {name: ENTITY_NAME.dataStorage, icon: "storage", route: "/admin/users"},
  [ENTITY_NAME.systemLogs]: {name: ENTITY_NAME.systemLogs, icon: "list_alt", route: "/admin/users"},
  [ENTITY_NAME.systemMonitor]: {name: ENTITY_NAME.systemMonitor, icon: "open_in_new", route: "/admin/users"},
  [ENTITY_NAME.uploadPortal]: {name: ENTITY_NAME.uploadPortal, icon: "backup", route: "/admin/users"},
  [ENTITY_NAME.systemStatus]: {name: ENTITY_NAME.systemStatus, icon: "monitor", route: "/admin/users"},
  [ENTITY_NAME.grafana]: {name: ENTITY_NAME.grafana, icon: "table_chart_view", route: "/admin/users"},
  // [ENTITY_NAME.grafana]: {name: ENTITY_NAME.grafana, icon: "open_in_new", route: "/admin/users"},
  [ENTITY_NAME.website]: {name: ENTITY_NAME.website, icon: "public", route: "/admin/users"},
  [ENTITY_NAME.wiki]: {name: ENTITY_NAME.wiki, icon: "menu_book", route: "/admin/users"},
}
